# Generated by Django 6.0 on 2026-01-10 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon_class', models.CharField(help_text='Sử dụng FontAwesome, ví dụ: fas fa-moon', max_length=50)),
                ('color', models.CharField(default='#ffcc00', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Slug từ Ophim (ví dụ: spider-man-no-way-home)', max_length=255, unique=True)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('origin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=50, null=True)),
                ('poster_url', models.URLField(max_length=500)),
                ('thumb_url', models.URLField(blank=True, max_length=500, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='Âu Mỹ', max_length=100)),
                ('is_series', models.BooleanField(default=False)),
                ('total_episodes', models.CharField(default='1', max_length=50)),
                ('current_episode', models.CharField(default='Full', help_text='Ví dụ: Tập 5 hoặc Hoàn tất', max_length=50)),
                ('imdb_rating', models.FloatField(default=0.0)),
                ('age_limit', models.IntegerField(default=0)),
                ('bunny_library_id', models.CharField(default='577395', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='Vietsub #1', max_length=100)),
                ('episode_name', models.CharField(help_text='Ví dụ: Tập 01, Full', max_length=100)),
                ('episode_slug', models.SlugField(max_length=100)),
                ('link_ophim', models.URLField(help_text='Link .m3u8 từ Ophim', max_length=1000)),
                ('link_bunny_id', models.CharField(blank=True, help_text='ID Video trên Bunny (nếu có)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.movie')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_unlocked', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
