# Generated by Django 6.0 on 2026-01-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(default='Đang cập nhật', max_length=100),
        ),
    ]
