# Generated by Django 6.0 on 2026-01-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_movie_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
