# Generated by Django 6.0 on 2026-01-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_cast_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_limit',
            field=models.IntegerField(default=0),
        ),
    ]
