# Generated by Django 6.0 on 2026-01-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movie_age_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
