# Generated by Django 6.0 on 2026-01-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_movie_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default='Âu Mỹ', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_episodes',
            field=models.IntegerField(default=1),
        ),
    ]
