# Generated by Django 6.0 on 2026-01-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_movie_api_id_alter_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
