# Generated by Django 6.0 on 2026-01-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_movie_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='views',
        ),
    ]
