# Generated by Django 6.0 on 2026-01-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_movie_country_movie_is_series_movie_total_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_episodes',
            field=models.CharField(default='1', help_text='Ví dụ: 12 hoặc Hoàn thành (12/12)', max_length=50),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, help_text='Tên tập (nếu có)', max_length=255)),
                ('video_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.movie')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
    ]
