# Generated by Django 6.0 on 2026-01-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_episode_episode_slug_alter_movie_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link_bunny_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link_ophim',
            field=models.TextField(help_text='Link .m3u8 từ Ophim'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='server_name',
            field=models.CharField(default='Vietsub #1', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='bunny_library_id',
            field=models.CharField(default='577395', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='current_episode',
            field=models.CharField(default='Full', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumb_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_episodes',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
