# Generated by Django 5.1.5 on 2026-01-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_review_sentiment_score_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sentiment_score',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
